server:
  servlet:
    context-path: /tretton37/elo/api

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.tretton37.ranking.elo: ${APP_LOG_LEVEL}

elo:
  ranking:
    initial-rank: ${APP_ELO_INITIAL_RANK}
    scaling: ${APP_ELO_SCALING}
    k-factor:
      min: ${APP_K_FACTOR_MIN}
      max: ${APP_K_FACTOR_MAX}
    games-threshold:
      min: ${APP_GAMES_THRESHOLD_MIN}
      max: ${APP_GAMES_THRESHOLD_MAX}