server:
  servlet:
    context-path: /tretton37/elo/api

spring:
  datasource:
    url: jdbc:postgresql://elo-db:5432/elo-ranking
    username: postgres
    password: F!T#cD64Z5eh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

elo:
  ranking:
    initial-rank: 1500
    scaling: 400
    k-factor:
      min: 10
      max: 40
    games-threshold:
      min: 10
      max: 30