server:
  servlet:
    context-path: /tretton37/elo/api
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.tretton37.ranking.elo: ${APP_LOG_LEVEL}

elo:
  ranking:
    initial-rank: ${APP_ELO_INITIAL_RANK}
    threshold-rank: ${APP_ELO_THRESHOLD_RANK}
    games-threshold: ${APP_GAMES_THRESHOLD}
    k-factor:
      min: ${APP_K_FACTOR_MIN}
      max: ${APP_K_FACTOR_MAX}